// data3.js
export const users = [
    {
        id: 1,
        name: "Asep Swazers",
        profilePic: "https://via.placeholder.com/150",
        shopType: "Electronics",
        orders: 120,
        mobile: "9876543210",
        email: "asep@example.com",
        address: "123 Main St, City, Country",
        govtId: "https://via.placeholder.com/100",
        description: "Sells a variety of electronic gadgets and appliances.",
        status: "Active",
    },
    {
        id: 2,
        name: "Thomas Slebew",
        profilePic: "https://via.placeholder.com/150",
        shopType: "Clothing",
        orders: 45,
        mobile: "9876543211",
        email: "thomas@example.com",
        address: "456 Elm St, City, Country",
        govtId: "https://via.placeholder.com/100",
        description: "Specializes in fashion and clothing.",
        status: "Disabled",
    },
    {
        id: 3,
        name: "Furqan Sebstian",
        profilePic: "https://via.placeholder.com/150",
        shopType: "Groceries",
        orders: 78,
        mobile: "9876543212",
        email: "furqan@example.com",
        address: "789 Oak St, City, Country",
        govtId: "https://via.placeholder.com/100",
        description: "Provides fresh groceries and produce.",
        status: "Warning",
    },
    {
        id: 4,
        name: "Delight",
        profilePic: "https://via.placeholder.com/150",
        shopType: "Furniture",
        orders: 102,
        mobile: "9876543213",
        email: "delight@example.com",
        address: "321 Maple St, City, Country",
        govtId: "https://via.placeholder.com/100",
        description: "Offers high-quality furniture.",
        status: "Active",
    },
    {
        id: 5,
        name: "Sophia Johnson",
        profilePic: "https://via.placeholder.com/150",
        shopType: "Bakery",
        orders: 63,
        mobile: "9876543214",
        email: "sophia@example.com",
        address: "654 Pine St, City, Country",
        govtId: "https://via.placeholder.com/100",
        description: "Bakes delicious cakes and pastries.",
        status: "Active",
    },
];
