export const cardData = [
  {
    id: 1,
    name: "Health Hub",
    description: "A well-stocked medical shop offering all essential medicines, health supplements, and first-aid items.",
    contact: "9876543210",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 22, City A",
    category: "Medical",
  },
  {
    id: 2,
    name: "Daily Rations",
    description: "Your go-to grocery store for fresh vegetables, fruits, and everyday household items.",
    contact: "9123456789",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 15, City A",
    category: "Grocery",
  },
  {
    id: 3,
    name: "Glam Spot",
    description: "A beauty store offering a wide range of skincare products, cosmetics, and personal care items.",
    contact: "9234567890",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 18, City A",
    category: "Beauty",
  },
  {
    id: 4,
    name: "Style Bazaar",
    description: "A trendy clothing store with collections for casual, formal, and festive occasions.",
    contact: "9345678901",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 12, City A",
    category: "Clothing",
  },
  {
    id: 5,
    name: "Power Essentials",
    description: "An electronics shop providing high-quality appliances, gadgets, and repair services.",
    contact: "9456789012",
    image: "https://via.placeholder.com/300x200",

    location: "Sector 20, City A",
    category: "Electronics",
  },
  {
    id: 6,
    name: "Fresh Farm",
    description: "Organic and fresh produce, directly sourced from local farms.",
    contact: "9567890123",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 5, City A",
    category: "Grocery",
  },
  {
    id: 7,
    name: "Bake Bliss",
    description: "A bakery known for its delicious cakes, pastries, and custom-made bakery items.",
    contact: "9678901234",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 7, City A",
    category: "Bakery",
  },
  {
    id: 8,
    name: "Book Haven",
    description: "A peaceful corner for book lovers, offering books, stationery, and other learning materials.",
    contact: "9789012345",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 9, City A",
    category: "Stationery",
  },
  {
    id: 9,
    name: "Fit Life",
    description: "A fitness store offering a wide range of gym equipment, accessories, and protein supplements.",
    contact: "9890123456",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 10, City A",
    category: "Fitness",
  },
  {
    id: 10,
    name: "Tech World",
    description: "A one-stop destination for the latest tech gadgets, accessories, and tech support.",
    contact: "9901234567",
    image: "https://via.placeholder.com/300x200",
    location: "Sector 16, City A",
    category: "Electronics",
  },
];

// Export for usage in other components
export default cardData;
